// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearAppLogs() {
  return window['go']['main']['App']['ClearAppLogs']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function CompareVersions(arg1, arg2) {
  return window['go']['main']['App']['CompareVersions'](arg1, arg2);
}

export function DownloadUpdate(arg1) {
  return window['go']['main']['App']['DownloadUpdate'](arg1);
}

export function GetAppLogPath() {
  return window['go']['main']['App']['GetAppLogPath']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetCCRVersion() {
  return window['go']['main']['App']['GetCCRVersion']();
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetLatestVersionFromGitHub() {
  return window['go']['main']['App']['GetLatestVersionFromGitHub']();
}

export function GetLogPath() {
  return window['go']['main']['App']['GetLogPath']();
}

export function GetServiceStatus() {
  return window['go']['main']['App']['GetServiceStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function ReadAppLogs() {
  return window['go']['main']['App']['ReadAppLogs']();
}

export function ReadLogs() {
  return window['go']['main']['App']['ReadLogs']();
}

export function ReadREADME() {
  return window['go']['main']['App']['ReadREADME']();
}

export function RestartService() {
  return window['go']['main']['App']['RestartService']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartService() {
  return window['go']['main']['App']['StartService']();
}

export function StopService() {
  return window['go']['main']['App']['StopService']();
}

export function TestLogging() {
  return window['go']['main']['App']['TestLogging']();
}
