// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearAppLogs():Promise<void>;

export function ClearLogs():Promise<void>;

export function GetAppLogPath():Promise<string>;

export function GetCCRVersion():Promise<string>;

export function GetConfigPath():Promise<string>;

export function GetLogPath():Promise<string>;

export function GetServiceStatus():Promise<main.ServiceStatus>;

export function Greet(arg1:string):Promise<string>;

export function LoadConfig():Promise<main.Config>;

export function ReadAppLogs():Promise<string>;

export function ReadLogs():Promise<string>;

export function ReadREADME():Promise<string>;

export function RestartService():Promise<void>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function StartService():Promise<void>;

export function StopService():Promise<void>;

export function TestLogging():Promise<string>;
